name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    # Comments about what to do in the steps
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on ${{ runner.os }} server hosted by Github!"
      - run: echo "This name of your branch is ${{  github.ref  }} and your repository is ${{ github.repository }}."
      - name: Check out Repository Code
        uses: actions/checkout@v2
      - run: echo "The github repository ${{ github.repository }} has been cloned to the runner."
      - run: echo "The workflow is ready to test your code on the runner."
      # Comments Says Something about Listing Files
      - name: List files in the repositoryy
      # Again Comments INSIDE
        run: |
          ls ${{ github.workspace }}
      # Purpose of Comments are unknown in this section
      - run: echo "This job's status is ${{ job.status }}."
      - run: az version
